#!/bin/bash

# Welcome to your first Bash Script
message='mama zimbe'
current_dir=$(pwd)
readonly vairable_wont_change="more"
echo "$message is talking to us from $current_dir and $vairable_wont_change"