#!/bin/bash
# This line tells the computer to use the Bash shell for running this script.

# A script that will create a resource group in Azure

setup() { 
    # Install the Azure Command Line Interface (CLI)
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    # Downloads and installs the Azure CLI.

    # Login to Azure
    az login --use-device-code
    # Opens a page for you to log in to Azure using a special code.

    echo "You're logged in."
    # Prints a message to let you know that you're logged in.
}

# Print out 5 recommended regions
print_out_regions() {
    regions_array=($( az account list-locations --query "[?metadata.regionCategory=='Recommended'].{Name:name}" -o tsv | head -n 5))
    # Gets a list of 5 recommended regions from Azure.

    for i in "${regions_array[@]}"
    do
       echo "$i"
       # Prints each recommended region.
    done
}

# Select a region
check_region() {
    local region_exists=false
    while [[ "$region_exists" = false ]];  do
        print_out_regions
        # Calls the function to show recommended regions.

        read -p "Enter your region: " selected_region
        # Asks you to type the name of the region you want to use.

        for j in "${regions_array[@]}"
        do
            if [[ "$selected_region" == "$j" ]]; then
                region_exists=true
                # Checks if the selected region is valid.
                echo "Region exists"
                # Prints a message saying the region exists.
                break
            else
                continue
            fi
        done
    done
}

# Check if resource group already exists.
check_resource_group () {
    while true; do
        read -p "Enter a name for your resource group: " resource_group
        # Asks you to type a name for your resource group.

        if [ $(az group exists --name $resource_group) = true ]; then 
            echo "The group $resource_group exists in your selected region, please provide another name..."
            # Checks if a group with that name already exists and asks you to choose another name.
        else
            break
        fi
    done
}

# Create the resource group
create_resource_group () {
    echo "Creating resource group: $resource_group in $selected_region"
    # Prints a message saying it's creating a resource group.

    az group create -g $resource_group -l $selected_region | grep provisioningState
    # Creates the resource group and shows the provisioningState (the state of creating resources).
}

# List all resource groups
list_resource_groups() {
    az group list -o table
    # Shows a list of all your resource groups in a nice table format.
}

# setup
check_region
check_resource_group 
create_resource_group
list_resource_groups
# Calls all the functions to set up, select a region, check for existing resource groups, create a resource group, and list all resource groups.
